export const ATTESTATION_KEY = "attestation"
export const SCHEDULE_KEY = "schedule"
export const ACCESS_TOKEN_KEY = "access-token"
export const REFRESH_TOKEN_KEY = "refresh-token"
export const EXAMS = "exams"
